
version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - npm install
  build:
    commands:
      - npm run build 
  post_build:
    commands:
      - mkdir deployment-package # Create a temporary directory 
      - cp -r build deployment-package/ # Copy build output
      - cp -r scripts deployment-package/ # Copy scrips 
      - cp appspec.yml deployment-package/
      - cp buildspec.yml deployment-package/

artifacts:
  files:
    - deployment-package/**/* # Package the temporary directory contents 
  base-directory: ./ # Specify the root for artifact collection