version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20.14.0
    commands:
      - echo Installing dependencies...
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - npm run build
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Zipping build files...
      - zip -r build.zip build/

artifacts:
  files:
    - build.zip
