version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20.14.0
    commands:
      - echo Installing dependencies...
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - npm run build
  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - '**/*'
  base-directory: build
  discard-paths: yes
